# Generated by Django 2.2.1 on 2019-08-24 18:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_login', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('site_password', models.CharField(max_length=30, verbose_name='Clave')),
                ('site_name', models.CharField(max_length=255, unique=True, verbose_name='Compañía')),
                ('site_url', models.CharField(max_length=300, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='SiteProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_name', models.CharField(max_length=255, unique=True, verbose_name='Proyecto')),
                ('prj_description', models.TextField(blank=True, verbose_name='Descripción')),
                ('prj_budget', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor estimado a pagar')),
                ('prj_creationdate', models.DateField(default=datetime.date.today, verbose_name='Fecha de creación')),
                ('prj_site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='admdesign.SiteAdmin')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDesigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prjdsg_login', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('prjdsg_firstname', models.CharField(max_length=255, verbose_name='Nombres')),
                ('prjdsg_lastname', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('prjdsg_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio solicitado')),
                ('prjdsg_uploaddate', models.DateField(default=datetime.date.today, verbose_name='Entregado')),
                ('prjdsg_status', models.CharField(choices=[('D', 'Disponible'), ('P', 'En proceso')], max_length=20, verbose_name='Estado')),
                ('prjdsg_original_url', models.CharField(editable=False, max_length=300)),
                ('prjdsg_processed_url', models.CharField(editable=False, max_length=300)),
                ('prjdsg_project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='admdesign.SiteProjects')),
            ],
        ),
    ]
