# Generated by Django 2.2.1 on 2019-08-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admdesign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdesigns',
            name='prjdsg_original_url',
        ),
        migrations.RemoveField(
            model_name='projectdesigns',
            name='prjdsg_processed_url',
        ),
        migrations.AddField(
            model_name='projectdesigns',
            name='prjdsg_original_file',
            field=models.ImageField(null=True, upload_to='originals'),
        ),
        migrations.AddField(
            model_name='projectdesigns',
            name='prjdsg_processed_file',
            field=models.ImageField(null=True, upload_to='processed'),
        ),
        migrations.AlterField(
            model_name='projectdesigns',
            name='prjdsg_status',
            field=models.CharField(choices=[('P', 'En proceso'), ('D', 'Disponible')], max_length=20, verbose_name='Estado'),
        ),
    ]
